config/routes.rb
ProjectB::Application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {registrations: 'registrations'}, :path => 'u'
  resources :users
  resources :books
  resources :friendships
  resources :loans
  get "friendships/accept/:id", to: "friendships#accept", as: :friendships_accept
  get "loans/request/:id", to: "loans#request_loan", as: :request_loan
  get "loans/accept/:id", to: "loans#accept", as: :accept_loan
  get "loans/return/:id", to: "loans#book_returned", as: :book_returned
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	has_many :loans
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
	def self.friendships_by_user(user_id)
		id = user_id
		@friendships = Friendship.select(:id, :user_id, :friend_id, :status).where(:user_id => id) | Friendship.select(:id, 'friend_id AS user_id', 'user_id AS friend_id', :status).where(:friend_id => id)
	end

	def self.friends_by_user(user_id)
		id = user_id
		@friendships = Friendship.select(:id, :user_id, :friend_id, :status).where(:user_id => id, :status => 1) | Friendship.select(:id, 'friend_id AS user_id', 'user_id AS friend_id', :status).where(:friend_id => id, :status => 1)
	end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :user
	belongs_to :book

	def self.n_requests_to_user(user_id)
		Loan.joins(:book).where('books.user_id' => user_id, 'loans.status' => 0).count
	end

	def self.requests_to_user(user_id)
		@loans = Loan.joins(:book).where('books.user_id' => user_id, 'loans.status' => 0)
	end

	def self.n_books_loaned(user_id)
		Loan.joins(:book).where('books.user_id' => user_id, 'loans.status' => 1).count
	end

	def self.books_loaned(user_id)
		@loans = Loan.joins(:book).where('books.user_id' => user_id, 'loans.status' => 1)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Friendship relationships
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :friendships, :source => :user
  has_many :books, dependent: :destroy
  has_many :loans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller? 
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @new_book = Book.new
  end

  def create
    @book = current_user.books.build(user_params)
    if @book.save
      flash[:success] = "¡Libro añadido!"
      redirect_to current_user
    else
      flash[:success] = "¡Error al crear el libro! ¡A correr en círculos!"
      redirect_to current_user
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(user_params)
      flash[:success] = "Libro actualizado"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      @book.destroy
    end
    flash[:notice] = "Removed book."
    redirect_to current_user
  end

  private
    def user_params
      params.require(:book).permit(:title, :author, :genre, :description)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
  	@friendship = current_user.friendships.build(:friend_id => params[:friend_id], :status => 0)
  	if @friendship.save
  		flash[:notice] = "Added friend."
  		redirect_to :back
  	else
  		flash[:error] = "Unable to add friend."
  		redirect_to :back
  	end
  end

  def accept
  	@friendship = current_user.inverse_friendships.find(params[:id])
  	@friendship.status = 1
  	@friendship.save
  	redirect_to :back
  end

  def destroy
  	@friendship = Friendship.find(params[:id])
  	if @friendship.user_id == current_user.id or @friendship.friend_id == current_user.id
  		@friendship.destroy
  	end
  	flash[:notice] = "Removed friendship."
  	redirect_to :back
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @loan = Loan.find(params[:id])
    @loan.destroy
    flash[:notice] = "Petición Denegada."
    redirect_to :back
  end

  def request_loan
    @book = Book.find(params[:id])
    if Loan.create!(:user_id => current_user.id, :book_id => @book.id, :status => 0)
      flash[:notice] = "Libro pedido."
      redirect_to @book
    else
      flash[:error] = "No se pudo pedir el libro."
      redirect_to @book
    end
  end

  def accept
    @loan = Loan.find(params[:id])
    @book = Book.find(@loan.book_id)
    @loan.status = 1
    @loan.save
    Loan.delete_all('book_id' => @book.id, 'status' => 0)
    flash[:notice] = "Libro prestado."
    redirect_to :back
  end

  def book_returned
    @loan = Loan.find(params[:id])
    @loan.status = 2
    @loan.save
    flash[:notice] = "Te devolvieron este libro."
    redirect_to :back
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end

	def create
		super
	end

	def update
		super
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    redirect_to new_user_registration_path
  end

  def create
  end

  def edit
    redirect_to edit_user_registration_path(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    size = options[:size]
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar img-responsive")
	  end
end

app/views/books/_book.html.erb
<div class="col-md-2">
	<div class="book-cover">
		<div class="book-title"><%= link_to @book.title, book_path(@book) %></div>
	</div>
	<br/>
</div>

app/views/books/create.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>
<% params.inspect %>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-lg-offset-3 col-lg-6" >
    <div class="container-fluid styled-container">
    	<h2 class="col-sm-offset-4">Editar datos del libro</h2>
    	<%= form_for @book, :html => { :method => :put, :class => "form-horizontal", :role => "form" } do |f| %>
    	<div class="form-group">
	        <%= f.label :title, "Título", :class => "col-sm-4 control-label" %>
	        <%= f.text_field :title, :autofocus => true, :class => "col-sm-7" %>
	    </div>
	    <div class="form-group">
	        <%= f.label :author, "Autor", :class => "col-sm-4 control-label" %>
	        <%= f.text_field :author, :class => "col-sm-7" %>
	    </div>
	    <div class="form-group">
	        <%= f.label :genre, "Autor", :class => "col-sm-4 control-label" %>
	        <%= f.collection_select :genre, Genre.all, :id, :name, :class => "col-sm-7" %>
	    </div>
	    <div class="form-group">
	        <%= f.label :description, "Descripción", :class => "col-sm-4 control-label" %>
	        <%= f.text_area :description, :rows => "5", :class => "col-sm-7" %>
	    </div>
	    <div class="form-group">
	        <%= f.submit "Actualizar Libro", :class => "btn btn-primary col-sm-offset-5" %>
	        <% end %>
	    </div>
    </div>
  </div>
</div>
</div>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<div class="row">
  	<div class="col-lg-offset-3 col-lg-6" >
    	<div class="container-fluid styled-container">
			<h2 class="col-sm-offset-4">Añadir un nuevo libro</h2>
			<%= form_for @new_book, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
			<div class="form-group">
		        <%= f.label :title, "Título", :class => "col-sm-4 control-label" %>
		        <%= f.text_field :title, :placeholder => "Título del Libro", :class => "col-sm-7" %>
		    </div>
		    <div class="form-group">
		        <%= f.label :author, "Autor", :class => "col-sm-4 control-label" %>
		        <%= f.text_field :author, :placeholder => "Nombre del Autor", :class => "col-sm-7" %>
		    </div>
		    <div class="form-group">
		        <%= f.label :genre, "Género", :class => "col-sm-4 control-label" %>
		        <%= f.collection_select :genre, Genre.all, :id, :name, :class => "col-sm-7" %>
		    </div>
		    <div class="form-group">
		        <%= f.label :description, "Descripción", :class => "col-sm-4 control-label" %>
		        <%= f.text_area :description, :placeholder => "Escribe una pequeña descripción del libro", :class => "col-sm-7", :rows => "5" %>
		    </div>
		    <div class="form-group">
		        <%= f.submit "Añadir Libro", :class => "btn btn-primary col-sm-offset-5" %>
				<% end %>
		    </div>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="styled-container col-md-offset-2 col-md-8">
	<div class="col-md-12">
		Título: <%= @book.title %><br/>
		Autor: <%= @book.author %><br/>
		Género: <%= Genre.find(@book.genre).name %><br/>
		Descripción: <%= @book.description %><br/>
		Dueño: <%= link_to User.find(@book.user_id).name, User.find(@book.user_id) %>
	</div>
	<% if @book.user_id == current_user.id %>
		<%= link_to "Eliminar libro", book_path(@book), :data => { :confirm => "¿Quieres eliminar el libro?" }, :method => :delete, :class => "btn btn-danger" %>
		<%= link_to "Editar Libro", edit_book_path(@book.id), :class => "btn btn-default" %>
	<% else %>
		<% if Friendship.where(:user_id => current_user.id, :friend_id => @book.user_id).count > 0 ||
			Friendship.where(:user_id => @book.user_id, :friend_id => current_user.id).count > 0 %>
			<% if @book.loans.where(:user_id => current_user.id, :status => 0).count > 0 %>
				Ya pediste el libro.
			<% elsif @book.loans.where(:status => 1).count == 0 %>
				<%= link_to "Pedir libro", request_loan_path(@book.id), :class => "btn btn-primary" %>
			<% else %>
				El libro está prestado
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/friendships/accept.html.erb
<h1>Friendships#accept</h1>
<p>Find me in app/views/friendships/accept.html.erb</p>

app/views/friendships/create.html.erb
<h1>Friendships#request</h1>
<p>Find me in app/views/friendships/request.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#remove</h1>
<p>Find me in app/views/friendships/remove.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer">
	<center>Aquí van a aparecer varios datos sobre el sitio y blablablablablabla</center>
</div>

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top top-banner" role="navigation">
	<% if true == false %>
		<p class='alert-success' role='alert'><%= notice %></p>
		<p class='alert-warning' role='alert'><%= alert %></p>
	<% end %>
	<div class="container-fluid">
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsed">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </button>
		    <%= link_to "TÍTULO", root_path, :class => "navbar-brand" %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapsed">
			<ul class="nav navbar-nav navbar-right">
				<% if !user_signed_in? %>
				<% if controller_name == 'sessions' %>
				<li class="active">
				<% else %>
				<li>
				<% end %>
				<%= link_to "Entrar", new_user_session_path %></li>

				<% if controller_name == 'registrations' %>
				<li class="active">
				<% else %>
				<li>
				<% end %>
				<%= link_to "Registrarse", new_user_registration_path %></li>

				<% else #Lo de abajo se ejecuta si el usuario está registrado%>
				<% if controller_name == 'users' and action_name == 'show' and current_user.id == @user.id %>
				<li class="active">
				<% else %>
				<li>
				<% end %>
				<%= link_to "Mi cuenta", current_user %></li>

				<% if controller_name == 'books' and action_name == 'new' %>
				<li class="active">
				<% else %>
				<li>
				<% end %>
				<%= link_to "Añadir Libro", new_book_path %></li>

				<% if controller_name == 'registrations' and action_name == 'edit' %>
				<li class="active">
				<% else %>
				<li>
				<% end %>
				<%= link_to "Editar Cuenta", edit_user_registration_path(current_user.id) %></li>

				<% if controller_name == 'users' and action_name == 'index' %>
				<li class="active">
				<% else %>
				<li>
				<% end %><%= link_to "Usuarios", users_path %></li>
				<li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectB</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="wrap">
	<div class="liquid-container">
		<%= render "layouts/top_navbar" %>
		<div class="row">
		<%= yield %>
		</div>		
	</div>
</div>
<%= render "layouts/footer" %>	
</body>
</html>

app/views/loans/create.html.erb
<h1>Loans#create</h1>
<p>Find me in app/views/loans/create.html.erb</p>

app/views/loans/destroy.html.erb
<h1>Loans#destroy</h1>
<p>Find me in app/views/loans/destroy.html.erb</p>

app/views/loans/edit.html.erb
<h1>Loans#edit</h1>
<p>Find me in app/views/loans/edit.html.erb</p>

app/views/loans/index.html.erb
<h1>Loans#index</h1>
<p>Find me in app/views/loans/index.html.erb</p>

app/views/loans/new.html.erb
<h1>Loans#new</h1>
<p>Find me in app/views/loans/new.html.erb</p>

app/views/loans/show.html.erb
<h1>Loans#show</h1>
<p>Find me in app/views/loans/show.html.erb</p>

app/views/loans/update.html.erb
<h1>Loans#update</h1>
<p>Find me in app/views/loans/update.html.erb</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
	<div class="col-md-12">
		Nombre: <%= current_user.name %></br>
		Correo: <%= current_user.email %>
	</div>
<% else %>
	<div class="col-lg-offset-1 col-lg-3">
		<H1>Bienvenido al sitio para prestarse libros</H1>
		<h2>Aquí podrás compartir libros con tus amigos y blablablablablabla</h2>
	</div>
	<div class="col-lg-7" >
		<%= image_tag("books.jpg", alt: "Una nena hipster", :class => "img-responsive", :style => "margin-top: 30px") %>
	</div>
<% end %>

app/views/users/_user.html.erb
<li class="user_small col-xs-12 col-sm-12 col-md-12">
	<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 panel panel-default panel-body">
  		<div class="col-xs-4 col-sm-2 col-md-2">
    			<%= gravatar_for user, size: 52 %>
  	  	</div>
  	  	<div class="col-xs-8 col-sm-6 user-data col-md-4">
    			<%= link_to user.name, user %><br>
    		</div>
        <div class="clearfix visible-xs-block hidden-md-block"></div>
    		<div class="col-xs-6 col-sm-2 col-md-2">
    			<%= link_to "Ver Perfil", user, :class => "btn btn-default" %>
    		</div>
    		<div class="col-xs-6 col-sm-2 col-md-2">
          <% if current_user != user %>
            <% #Existe una invitación de amigo
              if Friendship.where(:user_id => current_user.id, :friend_id => user.id, :status => 0).count > 0 %>
              <% friendship = Friendship.where(:user_id => current_user.id, :friend_id => user.id, :status => 0).select(:id)
                for friend in friendship
                  friendship_id = friend.id
                end
              %>
              <%= link_to "Cancelar invitación", friendship_path(:id => friendship_id), :data => { :confirm => "¿Quieres cancelar la invitación?" }, :method => :delete, :class => "btn btn-danger" %>
            <% #El usuario ya es amigo
              elsif Friendship.where(:user_id => current_user.id, :friend_id => user.id, :status => 1).count > 0 
                friendship = Friendship.where(:user_id => current_user.id, :friend_id => user.id, :status => 1).select(:id)
                for friend in friendship
                  friend
                end
                %>
                <%= link_to "Eliminar amigo", friend, :data => { :confirm => "¿Realmente quieres eliminar este amigo?" }, :method => :delete, :class => "btn btn-danger" %>
            <% #El usuario ya es amigo (En sentido inverso)
              elsif Friendship.where(:user_id => user.id, :friend_id => current_user.id, :status => 1).count > 0 
                friendship = Friendship.where(:user_id => user.id, :friend_id => current_user.id, :status => 1).select(:id)
                for friend in friendship
                  friend
                end
                %>
                <%= link_to "Eliminar amigo", friend, :data => { :confirm => "¿Realmente quieres eliminar este amigo?" }, :method => :delete, :class => "btn btn-danger" %>
            <% #El usuario no es amigo ni está invitado
              else %>
              <%= link_to "Añadir Amigo", friendships_path(:friend_id => user), :method => :post, :class => "btn btn-primary" %>
            <% end %>
            <% #Si el usuario actual es el mismo usuario de la lista, se deja el espacio en blanco %>
          <% end %>  			
    		</div>
      </div>
  	</div>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="styled-container col-md-offset-2 col-md-8">
	<div class="col-md-12">
		<h2>Usuarios</h2>
	</div>
	<ul class="users-list col-md-12">
	  <%= render @users %>
	</ul>
</div>

app/views/users/show.html.erb
<div class="styled-container col-md-offset-2 col-md-8">
	<div class="col-md-12">
		<h2><%= @user.name %></h2>
	</div>
	<div class="col-md-1">
		<%= gravatar_for @user, size: 52 %>
	</div>
	<div class="col-md-11">
		Aquí aparecerá información sobre el usuario.<br/><br/><br/><br/>
	</div>
	<ul class="nav nav-tabs" role="tablist">
	  <li class="active"><a href="#books" role="tab" data-toggle="tab">Libros</a></li>
	  <li><a href="#friends" role="tab" data-toggle="tab">Amigos</a></li>
	  <% if @user == current_user %>
	  <li><a href="#friend-requests" role="tab" data-toggle="tab">Solicitudes de amistad (<%= Friendship.where(:friend_id => current_user.id, :status => 0).count %>)</a></li>
	  <% end %>
	  <li><a href="#book-requests" role="tab" data-toggle="tab">Solicitudes de Libros (<%= Loan.n_requests_to_user(current_user) %>)</a></li>
	  <li><a href="#book-loaned" role="tab" data-toggle="tab">Libros prestados (<%= Loan.n_books_loaned(current_user) %>)</a></li>
	</ul>
	<div class="tab-content">
	  <div class="tab-pane fade in active" id="books">
	  	<div class="col-md-12">
			<h2>Libros del usuario</h2>
			<% for @book in @user.books %>
				<%= render "books/book" %>
			<% end %>
		</div>
	  </div>
	  <div class="tab-pane fade" id="friends">
	  	<div class="col-md-12">
			<h2>Lista de Amigos</h2>
			<% for friendship in Friendship.friends_by_user(@user.id) %>
				<%= render friendship.friend %>
			<% end %>
		</div>
	  </div>
	  <% if @user == current_user %>
	  <div class="tab-pane fade" id="friend-requests">
	  	<div class="col-md-12">			
			<h2> Solicitudes de amistad </h2>
			<% if @user.inverse_friendships.where("status = 0").count == 0 %>
				<p>No tienes solicitudes de amistad</p>
			<% end %>
			<% for friendship in @user.inverse_friendships.where("status = 0") %>
				<div class="col-xs-12 col-sm-6 col-md-6 panel panel-default panel-body">
					<div class="col-md-2">
					<%= gravatar_for friendship.user, size: 52 %>
					</div>
					<div class="col-md-3">
					<%= link_to friendship.user.name, friendship.user %>
					</div>
					<div class="col-md-1">
					<%= link_to "Aceptar solicitud", friendships_accept_path(friendship.id), :class => "btn btn-primary" %>
					</div>
				</div>
			<% end %>			
		</div>
	  </div>
	  <div class="tab-pane fade" id="book-requests">
	  	<div class="col-md-12">	
	  		<h2>Solicitudes de Libros</h2>
	  		<% if Loan.n_requests_to_user(current_user) == 0 %>
	  			No te han solicitado libros
	  		<% else %>
	  			<% for loan in Loan.requests_to_user(current_user) %>
	  				Libro: <%= loan.book.title %><br/>
	  				Pedido por: <%= User.find(loan.user_id).name %><br/>
	  				<%= link_to "Prestar Libro", accept_loan_path(:id => loan.id), :class => "btn btn-primary" %>
	  				<%= link_to "Rechazar solicitud", loan_path(:id => loan.id), :data => { :confirm => "¿Rechazar la solicitud?" }, :method => :delete, :class => "btn btn-danger" %><br/>
	  			<br/>
	  			<% end %>
	  		<% end %>
	  	</div>
	  </div>
	  <div class="tab-pane fade" id="book-loaned">
	  	<div class="col-md-12">	
	  		<h2>Libros Prestados</h2>
	  		<% for loan in Loan.books_loaned(current_user) %>
	  				Libro: <%= loan.book.title %><br/>
	  				Pedido por: <%= User.find(loan.user_id).name %><br/>
	  				<%= link_to "Te devolvieron este libro", book_returned_path(:id => loan.id), :class => "btn btn-primary" %>
	  				<br/>
	  			<br/>
	  			<% end %>
	  	</div>
	  </div>
	  <% end %>
	</div>	
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>